apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: develop
  labels:
    app: kafka-app
spec:
  serviceName: kafka-svc
  replicas: 1
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      labels:
        app: kafka-app
    spec:
      containers:
        - name: kafka-container
          image: confluentinc/cp-kafka:7.6.1 #To avoid kraft
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: KAFKA_BROKER_ID
              value: "1"

            # Listen on 0.0.0.0:9092 for PLAINTEXT
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092

            # Advertise the *service DNS* and same port to clients
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-svc.develop.svc.cluster.local:9092

            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"

            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-svc.develop.svc.cluster.local:2181"

            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT
          volumeMounts:
            - name: data
              mountPath: /mnt/kafka
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"